# Generated by Django 2.2.16 on 2020-11-09 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('Nails Solar Full Set', 'NF'), ('Solar P&W Full Set', 'NWP'), ('Powder Color Full Set', 'NPC'), ('Manicure Regular', 'MR'), ('Manicure Shellac', 'MS'), ('Pedicure Regular', 'PR'), ('Pedicure Shellac', 'PS'), ('Waxing', 'W'), ('Facial', 'F'), ('Eyelashes', 'E'), ('Massage', 'M'), ('Permanent Tattoo', 'T')], max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('provider', models.ForeignKey(blank=True, choices=[('Linh / Sugar', 'Linh'), ('Mia', 'Hien'), ('Jennifer', 'Nhung'), ('Theresa', 'Dung')], default=None, on_delete=django.db.models.deletion.CASCADE, to='WebApp.Employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
