# Generated by Django 2.2.16 on 2020-10-29 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default='', editable=False)),
                ('skills', models.CharField(choices=[('NF', 'Solar Full Set'), ('NPW', 'Solar P&W Full Set'), ('NPC', 'Powder Color Full Set'), ('M', 'Manicure Shellac'), ('P', 'Pedicure Shellac'), ('W', 'Waxing'), ('F', 'Facial'), ('E', 'Eyelashes'), ('M', 'Massage'), ('T', 'Permanent Tattoo')], max_length=100)),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default='')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_choices', models.CharField(choices=[('NF', 'Solar Full Set'), ('NFR', 'Solar Refill'), ('NPW', 'Solar P&W Full Set'), ('NPF', 'Solar P&W Refill'), ('NPC', 'Powder Color Full Set'), ('NPR', 'Powder Refill'), ('M', 'Manicure Shellac'), ('P', 'Pedicure Shellac'), ('W', 'Waxing'), ('F', 'Facial'), ('E', 'Eyelashes'), ('M', 'Massage'), ('T', 'Permanent Tattoo')], max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
