# Generated by Django 2.2.16 on 2020-11-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20201109_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.CharField(blank=True, choices=[('Linh', 'Linh / Sugar'), ('Hien', 'Mia'), ('Nhung', 'Jennifer'), ('Dung', 'Theresa')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.CharField(choices=[('NF', 'Nails Solar Full Set'), ('NWP', 'Solar P&W Full Set'), ('NPC', 'Powder Color Full Set'), ('MR', 'Manicure Regular'), ('MS', 'Manicure Shellac'), ('PR', 'Pedicure Regular'), ('PS', 'Pedicure Shellac'), ('W', 'Waxing'), ('F', 'Facial'), ('E', 'Eyelashes'), ('M', 'Massage'), ('T', 'Permanent Tattoo')], max_length=255),
        ),
    ]
