# Generated by Django 2.2.16 on 2020-09-14 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
