# Generated by Django 2.2.16 on 2020-10-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_auto_20201007_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(default='None', editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(default='None', editable=False),
        ),
    ]
