# Generated by Django 2.2.16 on 2020-10-08 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_auto_20201007_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='services',
            field=models.CharField(choices=[('NF', 'Solar Full Set'), ('NPW', 'Solar P&W Full Set'), ('NPC', 'Powder Color Full Set'), ('M', 'Manicure Shellac'), ('P', 'Pedicure Shellac'), ('W', 'Waxing'), ('F', 'Facial'), ('E', 'Eyelashes'), ('M', 'Massage'), ('T', 'Permanent Tattoo')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_performed',
            field=models.CharField(choices=[('NF', 'Solar Full Set'), ('NPW', 'Solar P&W Full Set'), ('NPC', 'Powder Color Full Set'), ('M', 'Manicure Shellac'), ('P', 'Pedicure Shellac'), ('W', 'Waxing'), ('F', 'Facial'), ('E', 'Eyelashes'), ('M', 'Massage'), ('T', 'Permanent Tattoo')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_price',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='yearly_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
