# Generated by Django 2.2.16 on 2020-10-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_auto_20201008_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='daily_total',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_total',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='service_id',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='service_price',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='weekly_total',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='yearly_total',
            field=models.IntegerField(default='', editable=False),
        ),
    ]
