# Generated by Django 2.2.16 on 2020-10-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_auto_20201009_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='daily_total',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='monthly_total',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='service_end',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='service_performed',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='service_price',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='service_start',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weekly_total',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='yearly_total',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
